graphs:
  - { type: grid, rows: 50, cols: 50 }
  - { type: er, n: 5000, p: 0.0008 }
  - { type: ba, n: 5000, m0: 5, m: 5 }
bounds: [25, 50, 100, 200]
sources_k: [4, 16]
trials: 5
seed: 42
maxw: 100
threads: [1, 2, 4]
